=== sshad0wtoxic/ordinario-ftw/xml/personajes.dtd
<!ELEMENT personajes (personaje+)>

<!ELEMENT personaje (
    nombre,
    especie,
    alineacion,
    genero,
    juegoDebut,
    velocidad,
    fuerza,
    inteligencia,
    descripcion,
    imagen
)>

<!ATTLIST personaje
    id ID #REQUIRED
>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT especie (#PCDATA)>

<!ELEMENT alineacion (#PCDATA)>

<!ELEMENT genero (#PCDATA)>

<!ELEMENT juegoDebut (#PCDATA)>

<!ELEMENT velocidad (#PCDATA)>

<!ELEMENT fuerza (#PCDATA)>

<!ELEMENT inteligencia (#PCDATA)>

<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT imagen (#PCDATA)>

=== sshad0wtoxic/ordinario-ftw/xml/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE personajes SYSTEM "personajes.dtd">

<personajes>

    <personaje id="p01">
        <nombre>Sonic the Hedgehog</nombre>
        <especie>Erizo</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Sonic the Hedgehog (1991)</juegoDebut>
        <velocidad>100</velocidad>
        <fuerza>80</fuerza>
        <inteligencia>75</inteligencia>
        <descripcion>El erizo más rápido del mundo y principal héroe de la franquicia Sonic.</descripcion>
        <imagen>img/personajes/sonic.png</imagen>
    </personaje>

    <personaje id="p02">
        <nombre>Miles "Tails" Prower</nombre>
        <especie>Zorro</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Sonic the Hedgehog 2 (1992)</juegoDebut>
        <velocidad>85</velocidad>
        <fuerza>60</fuerza>
        <inteligencia>100</inteligencia>
        <descripcion>Genio mecánico y mejor amigo de Sonic, capaz de volar usando sus dos colas.</descripcion>
        <imagen>img/personajes/tails.png</imagen>
    </personaje>

    <personaje id="p03">
        <nombre>Knuckles the Echidna</nombre>
        <especie>Equidna</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Sonic the Hedgehog 3 &amp; Knuckles (1994)</juegoDebut>
        <velocidad>75</velocidad>
        <fuerza>100</fuerza>
        <inteligencia>65</inteligencia>
        <descripcion>Guardián de la Master Emerald y protector de Angel Island.</descripcion>
        <imagen>img/personajes/knuckles.png</imagen>
    </personaje>

    <personaje id="p04">
        <nombre>Amy Rose</nombre>
        <especie>Erizo</especie>
        <alineacion>Heroe</alineacion>
        <genero>Femenino</genero>
        <juegoDebut>Sonic CD (1993)</juegoDebut>
        <velocidad>75</velocidad>
        <fuerza>85</fuerza>
        <inteligencia>70</inteligencia>
        <descripcion>Heroína optimista que combate usando su poderoso martillo Piko Piko.</descripcion>
        <imagen>img/personajes/amy.png</imagen>
    </personaje>

    <personaje id="p05">
        <nombre>Cream the Rabbit</nombre>
        <especie>Conejo</especie>
        <alineacion>Heroe</alineacion>
        <genero>Femenino</genero>
        <juegoDebut>Sonic Advance 2 (2002)</juegoDebut>
        <velocidad>65</velocidad>
        <fuerza>45</fuerza>
        <inteligencia>75</inteligencia>
        <descripcion>Coneja educada y amable que siempre está acompañada por Cheese, su Chao.</descripcion>
        <imagen>img/personajes/cream.png</imagen>
    </personaje>

    <personaje id="p06">
        <nombre>Espio the Chameleon</nombre>
        <especie>Camaleón</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Knuckles' Chaotix (1995)</juegoDebut>
        <velocidad>80</velocidad>
        <fuerza>70</fuerza>
        <inteligencia>85</inteligencia>
        <descripcion>Ninja del equipo Chaotix especializado en sigilo y espionaje.</descripcion>
        <imagen>img/personajes/espio.png</imagen>
    </personaje>

    <personaje id="p07">
        <nombre>Vector the Crocodile</nombre>
        <especie>Cocodrilo</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Knuckles' Chaotix (1995)</juegoDebut>
        <velocidad>60</velocidad>
        <fuerza>95</fuerza>
        <inteligencia>70</inteligencia>
        <descripcion>Líder de la Agencia de Detectives Chaotix y experto en investigaciones.</descripcion>
        <imagen>img/personajes/vector.png</imagen>
    </personaje>

    <personaje id="p08">
        <nombre>Charmy Bee</nombre>
        <especie>Abeja</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Knuckles' Chaotix (1995)</juegoDebut>
        <velocidad>75</velocidad>
        <fuerza>40</fuerza>
        <inteligencia>60</inteligencia>
        <descripcion>Miembro más joven de los Chaotix, siempre lleno de energía.</descripcion>
        <imagen>img/personajes/charmy.png</imagen>
    </personaje>

    <personaje id="p09">
        <nombre>Big the Cat</nombre>
        <especie>Gato</especie>
        <alineacion>Heroe</alineacion>
        <genero>Masculino</genero>
        <juegoDebut>Sonic Adventure (1998)</juegoDebut>
        <velocidad>40</velocidad>
        <fuerza>95</fuerza>
        <inteligencia>50</inteligencia>
        <descripcion>Gato gigante y tranquilo cuya principal preocupación es encontrar a Froggy.</descripcion>
        <imagen>img/personajes/big.png</imagen>
    </personaje>

    <personaje id="p10">
        <nombre>Blaze the Cat</nombre>
        <especie>Gato</especie>
        <alineacion>Heroe</alineacion>
        <genero>Femenino</genero>
        <juegoDebut>Sonic Rush (2005)</juegoDebut>
        <velocidad>90</velocidad>
        <fuerza>80</fuerza>
        <inteligencia>85</inteligencia>
        <descripcion>Princesa de la Dimensión Sol y guardiana de las Sol Emeralds.</descripcion>
        <imagen>img/personajes/blaze.png</imagen>
    </personaje>
<personaje id="p11">
    <nombre>Silver the Hedgehog</nombre>
    <especie>Erizo</especie>
    <alineacion>Heroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>Sonic the Hedgehog (2006)</juegoDebut>
    <velocidad>85</velocidad>
    <fuerza>75</fuerza>
    <inteligencia>85</inteligencia>
    <descripcion>Erizo proveniente de un futuro devastado que utiliza poderosas habilidades telequinéticas.</descripcion>
    <imagen>img/personajes/silver.png</imagen>
</personaje>

<personaje id="p12">
    <nombre>Tikal the Echidna</nombre>
    <especie>Equidna</especie>
    <alineacion>Heroe</alineacion>
    <genero>Femenino</genero>
    <juegoDebut>Sonic Adventure (1998)</juegoDebut>
    <velocidad>60</velocidad>
    <fuerza>50</fuerza>
    <inteligencia>90</inteligencia>
    <descripcion>Princesa de los antiguos equidnas que intentó detener la tragedia causada por Chaos.</descripcion>
    <imagen>img/personajes/tikal.png</imagen>
</personaje>

<personaje id="p13">
    <nombre>Mighty the Armadillo</nombre>
    <especie>Armadillo</especie>
    <alineacion>Heroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>SegaSonic the Hedgehog (1993)</juegoDebut>
    <velocidad>80</velocidad>
    <fuerza>90</fuerza>
    <inteligencia>70</inteligencia>
    <descripcion>Armadillo de gran corazón y extraordinaria resistencia física.</descripcion>
    <imagen>img/personajes/mighty.png</imagen>
</personaje>

<personaje id="p14">
    <nombre>Ray the Flying Squirrel</nombre>
    <especie>Ardilla voladora</especie>
    <alineacion>Heroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>SegaSonic the Hedgehog (1993)</juegoDebut>
    <velocidad>85</velocidad>
    <fuerza>55</fuerza>
    <inteligencia>70</inteligencia>
    <descripcion>Amigo de Mighty capaz de planear largas distancias gracias a sus membranas.</descripcion>
    <imagen>img/personajes/ray.png</imagen>
</personaje>

<personaje id="p15">
    <nombre>Marine the Raccoon</nombre>
    <especie>Mapache</especie>
    <alineacion>Heroe</alineacion>
    <genero>Femenino</genero>
    <juegoDebut>Sonic Rush Adventure (2007)</juegoDebut>
    <velocidad>65</velocidad>
    <fuerza>55</fuerza>
    <inteligencia>70</inteligencia>
    <descripcion>Joven aventurera con sueños de navegar por todo el mundo junto a Blaze.</descripcion>
    <imagen>img/personajes/marine.png</imagen>
</personaje>

<personaje id="p16">
    <nombre>Chip</nombre>
    <especie>Light Gaia</especie>
    <alineacion>Heroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>Sonic Unleashed (2008)</juegoDebut>
    <velocidad>70</velocidad>
    <fuerza>80</fuerza>
    <inteligencia>85</inteligencia>
    <descripcion>Encarnación de Light Gaia y aliado fundamental de Sonic durante la crisis de Dark Gaia.</descripcion>
    <imagen>img/personajes/chip.png</imagen>
</personaje>

<personaje id="p17">
    <nombre>E-102 Gamma</nombre>
    <especie>Robot</especie>
    <alineacion>Heroe</alineacion>
    <genero>Desconocido</genero>
    <juegoDebut>Sonic Adventure (1998)</juegoDebut>
    <velocidad>65</velocidad>
    <fuerza>95</fuerza>
    <inteligencia>80</inteligencia>
    <descripcion>Robot de combate creado por Eggman que se rebeló para liberar a sus hermanos robóticos.</descripcion>
    <imagen>img/personajes/gamma.png</imagen>
</personaje>

<personaje id="p18">
    <nombre>Shadow the Hedgehog</nombre>
    <especie>Erizo</especie>
    <alineacion>Antiheroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>Sonic Adventure 2 (2001)</juegoDebut>
    <velocidad>98</velocidad>
    <fuerza>90</fuerza>
    <inteligencia>85</inteligencia>
    <descripcion>La Forma de Vida Suprema creada por el Profesor Gerald Robotnik. Rival y aliado ocasional de Sonic.</descripcion>
    <imagen>img/personajes/shadow.png</imagen>
</personaje>

<personaje id="p19">
    <nombre>Chaos</nombre>
    <especie>Entidad de agua</especie>
    <alineacion>Antiheroe</alineacion>
    <genero>Desconocido</genero>
    <juegoDebut>Sonic Adventure (1998)</juegoDebut>
    <velocidad>80</velocidad>
    <fuerza>95</fuerza>
    <inteligencia>70</inteligencia>
    <descripcion>Antiguo guardián de los Chao que fue corrompido por el dolor y la ira.</descripcion>
    <imagen>img/personajes/chaos.png</imagen>
</personaje>

<personaje id="p20">
    <nombre>Jet the Hawk</nombre>
    <especie>Halcón</especie>
    <alineacion>Antiheroe</alineacion>
    <genero>Masculino</genero>
    <juegoDebut>Sonic Riders (2006)</juegoDebut>
    <velocidad>95</velocidad>
    <fuerza>75</fuerza>
    <inteligencia>70</inteligencia>
    <descripcion>Líder de los Babylon Rogues y autoproclamado corredor más rápido del mundo.</descripcion>
    <imagen>img/personajes/jet.png</imagen>
</personaje>

<personaje id="p21">
    <nombre>Rouge the Bat</nombre>
    <especie>Murciélago</especie>
